# Generated by Django 3.2.8 on 2021-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
